[package]
name = "todo-warp-rapidoc"
description = "Simple warp todo example api with utoipa and utoipa-rapidoc"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
  "Elli Example <example@example.com>"
]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10.0"
log = "0.4"
futures = "0.3"
utoipa = { path = "../../utoipa" }
utoipa-rapidoc = { path = "../../utoipa-rapidoc" }

[workspace]

