name: Git log
description: Mangles git log for change log
inputs:
  output-file:
    description: File path where to place the content of the changed commits
    required: true
runs:
  using: composite
  steps:
    - shell: bash 
      id: gitlog
      run: |
        ${{ github.action_path }}/gitlog.sh --output-file ${{ inputs.output-file }}
